name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./PharmatechBackend/PharmatechBackend/
          push: true
          tags: user/pharmatech/backend:latest
    #steps:
    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file PharmatechBackend/Dockerfile --tag backend:latest
